### ISSUE TITLE
ait-tlm-csv --fields argument isn't cooperating

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-Core#352]
User is running into issues when attempting to use the `--fields` argument to narrow down the output file data columns. Either this option isn't working at all due to a regression or we need to do a better job of explaining what the expected input format is in the `help` string.

**Comment by kmarwah** [comment]
PR #387 does not fix the issue. The issue stems from the fact that the fields file is being read using the 'rb' option, which yields an error message along the lines of:

`2022-01-18T13:20:41.927 | PROGRAM  | /Users/marwah/opt/anaconda3/envs/sunrise/bin/ait-tlm-csv --packet COMMAND_PROCESSOR_COMMAND_COUNTERS --csv /Users/marwah/Documents/SunRISE/SunRISE-IOS/test/csv_test.csv --fields /Users/marwah/Documents/SunRISE/SunRISE-IOS/test/fields_csv_test.txt /Users/marwah/Documents/SunRISE/SunRISE-IOS/test/csv_test.pcap
[b'accept_counter', b'reject_counter']
Traceback (most recent call last):
  File "/Users/marwah/opt/anaconda3/envs/sunrise/bin/ait-tlm-csv", line 8, in <module>
    sys.exit(main())
  File "/Users/marwah/opt/anaconda3/envs/sunrise/lib/python3.7/site-packages/ait/core/bin/ait_tlm_csv.py", line 95, in main
    raw = fldname.split('.')
TypeError: a bytes-like object is required, not 'str'`

The fix is to read the fields file using 'r'.

**Comment by nttoole** [comment]
Fixed by #387
