### ISSUE TITLE
Building from 1.0.0 Release error

### ISSUE THREAD

**Issue by gregoryjmiles** [NASA-AMMOS/AIT-Core#84]
No issue from cloning and checking out the release but downloading the *.tar.gz of the release and attempting to install with `pip install .` results in an error.

`Installing ait-create-dirs script to /[REDACTED]BLISS/BLISS_TLM/bin
    writing list of installed files to '/tmp/pip-Y7DFjv-record/install-record.txt'
    error: [Errno 2] No such file or directory: '.git/hooks`

**Comment by MJJoyce** [comment]
Hey @gregoryjmiles, thanks for throwing this ticket up here. This is due to it attempting to install a git hook without proper checks. We have a ticket open for it in #65 but haven't had a chance to get it fixed yet. You shouldn't run into any problem using the toolkit even though the error shows up.

I'm going to close this out as a duplicate and make sure we get #65 bumped up our priority list. Thanks again for opening the ticket

**Comment by MJJoyce** [comment]
FYI @gregoryjmiles, this should be taken care of once #88 is merged. Thanks again for poking us about this!
